"""Optional upstream link to the vendor cloud, so the official app keeps working.

When relay is enabled, each appliance session opens its own WebSocket to the
real cloud and we shuttle MQTT frames byte-for-byte in both directions. The
device's own credentials travel upstream unchanged, so from the cloud's point
of view the appliance is connected normally. We merely observe (to feed Home
Assistant) and inject (to control locally).

The REST bootstrap the device performs (login + time sync) is proxied the same
way so the device holds a genuine token.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import Awaitable, Callable

import aiohttp

from . import protocol

_LOGGER = logging.getLogger(__name__)

# Only these request headers are forwarded to the cloud; everything else
# (Host, Content-Length, hop-by-hop) is regenerated by aiohttp.
_FORWARDED_REQUEST_HEADERS = ("content-type", "authorization", "user-agent", "accept")

# Upper bound on a proxied REST response body. Real cloud responses (a login
# token, a timestamp) are tiny; this exists so a compromised or misbehaving
# "cloud" host can't make us buffer an unbounded body in memory. Read in
# chunks and aborted as soon as this is exceeded, rather than trusting
# Content-Length (which a malicious peer could simply lie about).
_MAX_PROXIED_RESPONSE_BYTES = 1024 * 1024
_PROXY_READ_CHUNK_BYTES = 65_536


class ProxyResponseTooLarge(Exception):
    """Raised when a proxied cloud REST response exceeds the size cap."""


class UpstreamConnection:
    """A single appliance's WebSocket to the vendor cloud."""

    def __init__(self, cloud_host: str, connect_timeout_seconds: float) -> None:
        self._cloud_host = cloud_host
        self._connect_timeout = connect_timeout_seconds
        self._session: aiohttp.ClientSession | None = None
        self._websocket: aiohttp.ClientWebSocketResponse | None = None

    @property
    def is_open(self) -> bool:
        return self._websocket is not None and not self._websocket.closed

    async def connect(self) -> None:
        """Open the upstream WebSocket with the MQTT subprotocol the device uses."""
        url = f"wss://{self._cloud_host}{protocol.WEBSOCKET_PATH}"
        self._session = aiohttp.ClientSession()
        try:
            self._websocket = await asyncio.wait_for(
                self._session.ws_connect(
                    url,
                    protocols=(protocol.WEBSOCKET_SUBPROTOCOL,),
                    heartbeat=None,  # the device's own MQTT PINGREQ keeps this alive
                    compress=0,  # no permessage-deflate: keep the relay byte-for-byte
                ),
                timeout=self._connect_timeout,
            )
        except Exception:
            await self.close()
            raise
        _LOGGER.debug("Upstream WebSocket open to %s", url)

    async def send(self, raw_frame: bytes) -> None:
        if not self.is_open:
            raise ConnectionError("upstream websocket is not open")
        await self._websocket.send_bytes(raw_frame)  # type: ignore[union-attr]

    async def receive_loop(self, on_frame: Callable[[bytes], Awaitable[None]]) -> None:
        """Deliver every upstream binary frame to ``on_frame`` until the socket closes."""
        assert self._websocket is not None
        async for message in self._websocket:
            if message.type == aiohttp.WSMsgType.BINARY:
                await on_frame(message.data)
            elif message.type in (aiohttp.WSMsgType.CLOSE, aiohttp.WSMsgType.CLOSING, aiohttp.WSMsgType.CLOSED):
                break
            elif message.type == aiohttp.WSMsgType.ERROR:
                _LOGGER.warning("Upstream WebSocket error: %s", self._websocket.exception())
                break
        _LOGGER.debug("Upstream WebSocket closed")

    async def close(self) -> None:
        if self._websocket is not None and not self._websocket.closed:
            await self._websocket.close()
        self._websocket = None
        if self._session is not None:
            await self._session.close()
        self._session = None


async def proxy_rest_request(
    cloud_host: str,
    method: str,
    path: str,
    request_headers: aiohttp.typedefs.LooseHeaders,
    body: bytes,
    timeout_seconds: float,
) -> tuple[int, str, bytes]:
    """Forward a device REST call to the cloud and return (status, content-type, body)."""
    url = f"https://{cloud_host}{path}"
    forwarded = {
        name: value
        for name, value in dict(request_headers).items()
        if name.lower() in _FORWARDED_REQUEST_HEADERS
    }
    timeout = aiohttp.ClientTimeout(total=timeout_seconds)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.request(method, url, headers=forwarded, data=body or None) as response:
            payload = bytearray()
            async for chunk in response.content.iter_chunked(_PROXY_READ_CHUNK_BYTES):
                payload += chunk
                if len(payload) > _MAX_PROXIED_RESPONSE_BYTES:
                    raise ProxyResponseTooLarge(
                        f"cloud response for {path} exceeded {_MAX_PROXIED_RESPONSE_BYTES} bytes"
                    )
            return response.status, response.headers.get("Content-Type", "application/json"), bytes(payload)
